export interface Aide {
  id: number;
  nom: string;
  type: 'particulier' | 'entreprise' | 'association';
  profilEligible: string[];
  situationEligible: string[];
  montantMax: number;
  description: string;
  urlOfficielle: string;
  region: string | null;
  handicapOnly: boolean;
  badge: 'probable' | 'possible' | 'verifier';
}

export const AIDES: Aide[] = [
  // PARTICULIERS (20)
  { id: 1, nom: "CPF - Compte Personnel de Formation", type: 'particulier', profilEligible: ['particulier'], situationEligible: ['salarie', 'demandeur_emploi', 'independant'], montantMax: 5000, description: "Financez votre formation professionnelle avec votre solde CPF.", urlOfficielle: "https://www.moncompteformation.gouv.fr", region: null, handicapOnly: false, badge: 'probable' },
  { id: 2, nom: "AIF - Aide Individuelle a la Formation", type: 'particulier', profilEligible: ['particulier'], situationEligible: ['demandeur_emploi'], montantMax: 8000, description: "France Travail finance tout ou partie de votre formation.", urlOfficielle: "https://www.francetravail.fr", region: null, handicapOnly: false, badge: 'probable' },
  { id: 3, nom: "Cheque Formation CAF", type: 'particulier', profilEligible: ['particulier'], situationEligible: ['salarie', 'demandeur_emploi', 'rsa'], montantMax: 500, description: "Aide de la CAF pour financer une formation ou un outil numerique.", urlOfficielle: "https://www.caf.fr", region: null, handicapOnly: false, badge: 'possible' },
  { id: 4, nom: "Pass Numerique", type: 'particulier', profilEligible: ['particulier'], situationEligible: ['salarie', 'demandeur_emploi', 'retraite', 'rsa'], montantMax: 20, description: "Cheques de 10 a 20 euros pour des services numeriques.", urlOfficielle: "https://www.passnumerique.fr", region: null, handicapOnly: false, badge: 'possible' },
  { id: 5, nom: "Prime d'activite", type: 'particulier', profilEligible: ['particulier'], situationEligible: ['salarie', 'independant', 'auto_entrepreneur'], montantMax: 600, description: "Complement de revenus pour les travailleurs aux ressources modestes.", urlOfficielle: "https://www.caf.fr/allocataires/droits-et-prestations/connaitre-vos-droits-selon-votre-situation/vous-travaillez/la-prime-d-activite", region: null, handicapOnly: false, badge: 'probable' },
  { id: 6, nom: "AGEFIPH - Aide aux travailleurs handicapes", type: 'particulier', profilEligible: ['particulier'], situationEligible: ['salarie', 'demandeur_emploi', 'independant'], montantMax: 10000, description: "Financement de formations et outils pour personnes en situation de handicap.", urlOfficielle: "https://www.agefiph.fr", region: null, handicapOnly: true, badge: 'probable' },
  { id: 7, nom: "FIPHFP", type: 'particulier', profilEligible: ['particulier'], situationEligible: ['salarie'], montantMax: 10000, description: "Fonds pour l'insertion des personnes handicapees dans la fonction publique.", urlOfficielle: "https://www.fiphfp.fr", region: null, handicapOnly: true, badge: 'verifier' },
  { id: 8, nom: "Aide a la mobilite pour les jeunes", type: 'particulier', profilEligible: ['particulier', 'etudiant'], situationEligible: ['demandeur_emploi', 'etudiant'], montantMax: 5000, description: "Aide pour les jeunes en formation eloignes de leur domicile.", urlOfficielle: "https://www.francetravail.fr", region: null, handicapOnly: false, badge: 'possible' },
  { id: 9, nom: "Bourse CROUS", type: 'particulier', profilEligible: ['etudiant'], situationEligible: ['etudiant'], montantMax: 6000, description: "Bourse sur criteres sociaux pour les etudiants.", urlOfficielle: "https://www.messervices.etudiant.gouv.fr", region: null, handicapOnly: false, badge: 'probable' },
  { id: 10, nom: "Pass Culture", type: 'particulier', profilEligible: ['particulier', 'etudiant'], situationEligible: ['etudiant', 'salarie', 'demandeur_emploi'], montantMax: 300, description: "300 euros pour les 15-20 ans, utilisables pour des outils numeriques educatifs.", urlOfficielle: "https://pass.culture.fr", region: null, handicapOnly: false, badge: 'probable' },
  { id: 11, nom: "Micro-credit personnel", type: 'particulier', profilEligible: ['particulier'], situationEligible: ['salarie', 'demandeur_emploi', 'rsa', 'independant'], montantMax: 5000, description: "Pret a taux reduit pour les personnes exclues du credit bancaire classique.", urlOfficielle: "https://www.france-microcredit.org", region: null, handicapOnly: false, badge: 'possible' },
  { id: 12, nom: "OPCO - Operateur de competences", type: 'particulier', profilEligible: ['particulier'], situationEligible: ['salarie'], montantMax: 8000, description: "Votre OPCO finance vos formations liees a votre metier.", urlOfficielle: "https://www.opco.fr", region: null, handicapOnly: false, badge: 'probable' },
  { id: 13, nom: "1jeune1solution", type: 'particulier', profilEligible: ['particulier', 'etudiant'], situationEligible: ['demandeur_emploi', 'etudiant'], montantMax: 5000, description: "Aides a la formation et a l'emploi pour les moins de 30 ans.", urlOfficielle: "https://www.1jeune1solution.gouv.fr", region: null, handicapOnly: false, badge: 'probable' },
  { id: 14, nom: "Garantie Jeunes / CEJ", type: 'particulier', profilEligible: ['particulier'], situationEligible: ['demandeur_emploi'], montantMax: 500, description: "Allocation mensuelle de 500 euros pour les jeunes en insertion.", urlOfficielle: "https://www.service-public.fr", region: null, handicapOnly: false, badge: 'possible' },
  { id: 15, nom: "PLIE - Plan Local pour l'Insertion", type: 'particulier', profilEligible: ['particulier'], situationEligible: ['demandeur_emploi', 'rsa'], montantMax: 3000, description: "Accompagnement et financement de formation au niveau local.", urlOfficielle: "https://www.service-public.fr", region: null, handicapOnly: false, badge: 'verifier' },
  { id: 16, nom: "RSA - Complement formation", type: 'particulier', profilEligible: ['particulier'], situationEligible: ['rsa'], montantMax: 1000, description: "Complement RSA pour les beneficiaires en formation.", urlOfficielle: "https://www.service-public.fr", region: null, handicapOnly: false, badge: 'probable' },
  { id: 17, nom: "FNE-Formation", type: 'particulier', profilEligible: ['particulier'], situationEligible: ['salarie'], montantMax: 5000, description: "Financement a 100% des formations pour les salaries en activite partielle.", urlOfficielle: "https://travail-emploi.gouv.fr", region: null, handicapOnly: false, badge: 'probable' },
  { id: 18, nom: "Transition Professionnelle (PTP)", type: 'particulier', profilEligible: ['particulier'], situationEligible: ['salarie'], montantMax: 15000, description: "Financement a 100% d'une reconversion professionnelle.", urlOfficielle: "https://www.transitionspro.fr", region: null, handicapOnly: false, badge: 'probable' },
  { id: 19, nom: "VAE - Validation des Acquis", type: 'particulier', profilEligible: ['particulier'], situationEligible: ['salarie', 'demandeur_emploi', 'independant'], montantMax: 3000, description: "Faites reconnaitre votre experience par un diplome.", urlOfficielle: "https://www.vae.gouv.fr", region: null, handicapOnly: false, badge: 'possible' },
  { id: 20, nom: "Pole Emploi Numerique", type: 'particulier', profilEligible: ['particulier'], situationEligible: ['demandeur_emploi'], montantMax: 2000, description: "Formations numeriques financees par France Travail.", urlOfficielle: "https://www.francetravail.fr", region: null, handicapOnly: false, badge: 'probable' },
  // ENTREPRISES (15)
  { id: 21, nom: "France Num - Cheque numerique", type: 'entreprise', profilEligible: ['entreprise'], situationEligible: ['independant', 'auto_entrepreneur'], montantMax: 6500, description: "Subvention pour la transition numerique des TPE/PME.", urlOfficielle: "https://www.francenum.gouv.fr", region: null, handicapOnly: false, badge: 'probable' },
  { id: 22, nom: "Pack IA Booster", type: 'entreprise', profilEligible: ['entreprise'], situationEligible: ['independant', 'auto_entrepreneur'], montantMax: 18500, description: "Aide specifique pour l'integration de l'IA en entreprise.", urlOfficielle: "https://www.bpifrance.fr", region: null, handicapOnly: false, badge: 'possible' },
  { id: 23, nom: "OPCO IA & Digital", type: 'entreprise', profilEligible: ['entreprise'], situationEligible: ['independant'], montantMax: 10000, description: "Formation des salaries a l'IA par votre OPCO.", urlOfficielle: "https://www.opco.fr", region: null, handicapOnly: false, badge: 'probable' },
  { id: 24, nom: "BFC Numerique", type: 'entreprise', profilEligible: ['entreprise'], situationEligible: ['independant', 'auto_entrepreneur'], montantMax: 5000, description: "Aide regionale Bourgogne-Franche-Comte pour le numerique.", urlOfficielle: "https://www.bourgognefranchecomte.fr", region: 'Bourgogne-Franche-Comte', handicapOnly: false, badge: 'verifier' },
  { id: 25, nom: "CIR - Credit d'Impot Recherche", type: 'entreprise', profilEligible: ['entreprise'], situationEligible: ['independant'], montantMax: 100000, description: "30% de credit d'impot sur les depenses de R&D.", urlOfficielle: "https://www.enseignementsup-recherche.gouv.fr", region: null, handicapOnly: false, badge: 'probable' },
  { id: 26, nom: "CII - Credit d'Impot Innovation", type: 'entreprise', profilEligible: ['entreprise'], situationEligible: ['independant', 'auto_entrepreneur'], montantMax: 80000, description: "20% de credit d'impot sur les depenses d'innovation.", urlOfficielle: "https://www.impots.gouv.fr", region: null, handicapOnly: false, badge: 'probable' },
  { id: 27, nom: "FNE-Formation IA", type: 'entreprise', profilEligible: ['entreprise'], situationEligible: ['independant'], montantMax: 15000, description: "Financement de formations IA pour vos salaries.", urlOfficielle: "https://travail-emploi.gouv.fr", region: null, handicapOnly: false, badge: 'probable' },
  { id: 28, nom: "TPE CCI - Aide numerique", type: 'entreprise', profilEligible: ['entreprise'], situationEligible: ['independant', 'auto_entrepreneur'], montantMax: 1500, description: "Aide des CCI pour la numerisation des tres petites entreprises.", urlOfficielle: "https://www.cci.fr", region: null, handicapOnly: false, badge: 'possible' },
  { id: 29, nom: "AGEFIPH Entreprise", type: 'entreprise', profilEligible: ['entreprise'], situationEligible: ['independant'], montantMax: 10000, description: "Aides pour l'emploi de personnes handicapees en entreprise.", urlOfficielle: "https://www.agefiph.fr", region: null, handicapOnly: true, badge: 'possible' },
  { id: 30, nom: "DIRECCTE / DREETS", type: 'entreprise', profilEligible: ['entreprise'], situationEligible: ['independant'], montantMax: 20000, description: "Aides regionales a la transition numerique.", urlOfficielle: "https://dreets.gouv.fr", region: null, handicapOnly: false, badge: 'verifier' },
  { id: 31, nom: "Diagnostic BFC 50%", type: 'entreprise', profilEligible: ['entreprise'], situationEligible: ['independant', 'auto_entrepreneur'], montantMax: 5000, description: "50% de prise en charge d'un diagnostic numerique en BFC.", urlOfficielle: "https://www.bourgognefranchecomte.fr", region: 'Bourgogne-Franche-Comte', handicapOnly: false, badge: 'verifier' },
  { id: 32, nom: "BPI France - Pret numerique", type: 'entreprise', profilEligible: ['entreprise'], situationEligible: ['independant'], montantMax: 300000, description: "Pret pour la transformation numerique des PME.", urlOfficielle: "https://www.bpifrance.fr", region: null, handicapOnly: false, badge: 'possible' },
  { id: 33, nom: "DETR - Dotation Equipement Territoires", type: 'entreprise', profilEligible: ['entreprise'], situationEligible: ['independant'], montantMax: 50000, description: "Subvention pour les projets numeriques en milieu rural.", urlOfficielle: "https://www.collectivites-locales.gouv.fr", region: null, handicapOnly: false, badge: 'verifier' },
  { id: 34, nom: "FEDER - Fonds europeen", type: 'entreprise', profilEligible: ['entreprise'], situationEligible: ['independant'], montantMax: 100000, description: "Financement europeen pour l'innovation numerique.", urlOfficielle: "https://www.europe-en-france.gouv.fr", region: null, handicapOnly: false, badge: 'verifier' },
  { id: 35, nom: "Aide sante numerique", type: 'entreprise', profilEligible: ['entreprise'], situationEligible: ['independant'], montantMax: 15000, description: "Aide specifique pour la numerisation du secteur sante.", urlOfficielle: "https://esante.gouv.fr", region: null, handicapOnly: false, badge: 'possible' },
  // ASSOCIATIONS (10)
  { id: 36, nom: "FDVA2 - Fonctionnement", type: 'association', profilEligible: ['association'], situationEligible: ['independant'], montantMax: 15000, description: "Subvention de fonctionnement pour les associations.", urlOfficielle: "https://www.associations.gouv.fr", region: null, handicapOnly: false, badge: 'probable' },
  { id: 37, nom: "FDVA3 - Innovation", type: 'association', profilEligible: ['association'], situationEligible: ['independant'], montantMax: 10000, description: "Subvention pour les projets innovants des associations.", urlOfficielle: "https://www.associations.gouv.fr", region: null, handicapOnly: false, badge: 'possible' },
  { id: 38, nom: "Subvention communale", type: 'association', profilEligible: ['association'], situationEligible: ['independant'], montantMax: 5000, description: "Aide de votre commune pour les associations locales.", urlOfficielle: "https://www.service-public.fr", region: null, handicapOnly: false, badge: 'possible' },
  { id: 39, nom: "LEADER - Developpement rural", type: 'association', profilEligible: ['association'], situationEligible: ['independant'], montantMax: 20000, description: "Programme europeen pour le developpement en milieu rural.", urlOfficielle: "https://www.europe-en-france.gouv.fr", region: null, handicapOnly: false, badge: 'verifier' },
  { id: 40, nom: "Aide departementale", type: 'association', profilEligible: ['association'], situationEligible: ['independant'], montantMax: 10000, description: "Subvention de votre conseil departemental.", urlOfficielle: "https://www.service-public.fr", region: null, handicapOnly: false, badge: 'possible' },
  { id: 41, nom: "Aide regionale BFC", type: 'association', profilEligible: ['association'], situationEligible: ['independant'], montantMax: 15000, description: "Subvention de la region Bourgogne-Franche-Comte.", urlOfficielle: "https://www.bourgognefranchecomte.fr", region: 'Bourgogne-Franche-Comte', handicapOnly: false, badge: 'verifier' },
  { id: 42, nom: "Fondation de France", type: 'association', profilEligible: ['association'], situationEligible: ['independant'], montantMax: 15000, description: "Subventions de la Fondation de France pour les associations.", urlOfficielle: "https://www.fondationdefrance.org", region: null, handicapOnly: false, badge: 'possible' },
  { id: 43, nom: "Mecenat d'entreprise", type: 'association', profilEligible: ['association'], situationEligible: ['independant'], montantMax: 50000, description: "60% de reduction d'impot pour les entreprises mecenes.", urlOfficielle: "https://www.associations.gouv.fr", region: null, handicapOnly: false, badge: 'possible' },
  { id: 44, nom: "Google Ad Grants", type: 'association', profilEligible: ['association'], situationEligible: ['independant'], montantMax: 10000, description: "10 000$/mois de publicite Google gratuite pour les associations.", urlOfficielle: "https://www.google.com/grants", region: null, handicapOnly: false, badge: 'probable' },
  { id: 45, nom: "France Active", type: 'association', profilEligible: ['association'], situationEligible: ['independant'], montantMax: 30000, description: "Financement et accompagnement pour les structures d'utilite sociale.", urlOfficielle: "https://www.franceactive.org", region: null, handicapOnly: false, badge: 'possible' },
];
